daysUntilStale: 14
daysUntilClose: 3
exemptLabels:
  - "Priority: Critical"
  - "Priority: High"
  - "Priority: Medium"
  - "Priority: Low"
  - "State: Conversation"
  - "State: Help Wanted"
  - "State: Postponed"
  - "State: Unassigned"
  - "State: Work in Progress"
  - "Type: Bug"
  - "Type: Enhancement"
  - "Type: Dependencies"
  - "Type: Infrastructure"
staleLabel: 'Meta: Abandoned'
markComment: >
  This submission has been flagged as abandoned due to lack of activity. Please leave a comment if this issue has not yet been resolved, otherwise it will be automatically closed.
closeComment: >
  Following with the previous comment, this submission has been automatically closed due to inactivity.
